Node IP: 128.55.82.143
srun: Job 28985899 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=28985899.1
W0804 01:45:02.773000 140195233676160 torch/distributed/run.py:757] 
W0804 01:45:02.773000 140195233676160 torch/distributed/run.py:757] *****************************************
W0804 01:45:02.773000 140195233676160 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0804 01:45:02.773000 140195233676160 torch/distributed/run.py:757] *****************************************
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188] Starting elastic_operator with launch configs:
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   entrypoint       :  
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   min_nodes        : 2
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   max_nodes        : 2
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   nproc_per_node   : 4
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   run_id           : 24487
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   rdzv_backend     : c10d
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   rdzv_endpoint    : 128.55.82.143:29500
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   rdzv_configs     : {'timeout': 900}
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   max_restarts     : 0
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   monitor_interval : 5
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   log_dir          : /tmp/torchelastic_y1ep2x9n
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188]   metrics_cfg      : {}
I0804 01:45:02.773000 140195233676160 torch/distributed/launcher/api.py:188] 
I0804 01:45:02.791000 140195233676160 torch/distributed/elastic/agent/server/api.py:866] [default] starting workers for entrypoint: python3.10
I0804 01:45:02.791000 140195233676160 torch/distributed/elastic/agent/server/api.py:699] [default] Rendezvous'ing worker group
W0804 01:45:03.207000 140122861398912 torch/distributed/run.py:757] 
W0804 01:45:03.207000 140122861398912 torch/distributed/run.py:757] *****************************************
W0804 01:45:03.207000 140122861398912 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0804 01:45:03.207000 140122861398912 torch/distributed/run.py:757] *****************************************
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188] Starting elastic_operator with launch configs:
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   entrypoint       :  
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   min_nodes        : 2
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   max_nodes        : 2
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   nproc_per_node   : 4
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   run_id           : 24487
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   rdzv_backend     : c10d
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   rdzv_endpoint    : 128.55.82.143:29500
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   rdzv_configs     : {'timeout': 900}
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   max_restarts     : 0
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   monitor_interval : 5
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   log_dir          : /tmp/torchelastic_r4p7ft5c
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188]   metrics_cfg      : {}
I0804 01:45:03.207000 140122861398912 torch/distributed/launcher/api.py:188] 
I0804 01:45:03.230000 140122861398912 torch/distributed/elastic/agent/server/api.py:866] [default] starting workers for entrypoint: python3.10
I0804 01:45:03.231000 140122861398912 torch/distributed/elastic/agent/server/api.py:699] [default] Rendezvous'ing worker group
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568] [default] Rendezvous complete for workers. Result:
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   restart_count=0
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   master_addr=nid008320-hsn0
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   master_port=32793
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   group_rank=0
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   group_world_size=2
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   local_ranks=[0, 1, 2, 3]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   role_ranks=[0, 1, 2, 3]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   global_ranks=[0, 1, 2, 3]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   role_world_sizes=[8, 8, 8, 8]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568]   global_world_sizes=[8, 8, 8, 8]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:568] 
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/api.py:707] [default] Starting worker group
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568] [default] Rendezvous complete for workers. Result:
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   restart_count=0
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   master_addr=nid008320-hsn0
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   master_port=32793
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   group_rank=1
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   group_world_size=2
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   local_ranks=[0, 1, 2, 3]
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   role_ranks=[4, 5, 6, 7]
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/agent/server/local_elastic_agent.py:168] Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   global_ranks=[4, 5, 6, 7]
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   role_world_sizes=[8, 8, 8, 8]
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568]   global_world_sizes=[8, 8, 8, 8]
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:568] 
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:263] log directory set to: /tmp/torchelastic_y1ep2x9n/24487_ucojw8l6
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/api.py:707] [default] Starting worker group
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker0 reply file to: /tmp/torchelastic_y1ep2x9n/24487_ucojw8l6/attempt_0/0/error.json
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/agent/server/local_elastic_agent.py:168] Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
I0804 01:45:04.559000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker1 reply file to: /tmp/torchelastic_y1ep2x9n/24487_ucojw8l6/attempt_0/1/error.json
I0804 01:45:04.559000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:263] log directory set to: /tmp/torchelastic_r4p7ft5c/24487_y6y7xppw
I0804 01:45:04.560000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker2 reply file to: /tmp/torchelastic_y1ep2x9n/24487_ucojw8l6/attempt_0/2/error.json
I0804 01:45:04.560000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker0 reply file to: /tmp/torchelastic_r4p7ft5c/24487_y6y7xppw/attempt_0/0/error.json
I0804 01:45:04.560000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker3 reply file to: /tmp/torchelastic_y1ep2x9n/24487_ucojw8l6/attempt_0/3/error.json
I0804 01:45:04.560000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker1 reply file to: /tmp/torchelastic_r4p7ft5c/24487_y6y7xppw/attempt_0/1/error.json
I0804 01:45:04.560000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker2 reply file to: /tmp/torchelastic_r4p7ft5c/24487_y6y7xppw/attempt_0/2/error.json
I0804 01:45:04.560000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker3 reply file to: /tmp/torchelastic_r4p7ft5c/24487_y6y7xppw/attempt_0/3/error.json
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
E0804 01:45:09.573000 140195233676160 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 1193449) of binary: /global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10
E0804 01:45:09.577000 140122861398912 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 1204121) of binary: /global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10
I0804 01:45:09.723000 140122861398912 torch/distributed/elastic/multiprocessing/errors/__init__.py:360] ('local_rank %s FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html', 4)
Traceback (most recent call last):
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
  FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-04_01:45:09
  host      : nid008356-hsn0
  rank      : 5 (local_rank: 1)
  exitcode  : 2 (pid: 1204122)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-04_01:45:09
  host      : nid008356-hsn0
  rank      : 6 (local_rank: 2)
  exitcode  : 2 (pid: 1204123)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-04_01:45:09
  host      : nid008356-hsn0
  rank      : 7 (local_rank: 3)
  exitcode  : 2 (pid: 1204124)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-04_01:45:09
  host      : nid008356-hsn0
  rank      : 4 (local_rank: 0)
  exitcode  : 2 (pid: 1204121)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
I0804 01:45:09.929000 140195233676160 torch/distributed/elastic/multiprocessing/errors/__init__.py:360] ('local_rank %s FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html', 0)
Traceback (most recent call last):
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
  FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-04_01:45:09
  host      : nid008320-hsn0
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 1193450)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-04_01:45:09
  host      : nid008320-hsn0
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 1193451)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-04_01:45:09
  host      : nid008320-hsn0
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 1193452)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-04_01:45:09
  host      : nid008320-hsn0
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1193449)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: nid008356: task 1: Exited with exit code 1
srun: Terminating StepId=28985899.1
srun: error: nid008320: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/dist-training.py", line 277, in <module>
    ddp_setup()
  File "/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/utils/misc.py", line 50, in ddp_setup
    init_process_group(backend="nccl")
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1305, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 234, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 219, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
