Node IP: 128.55.67.80
W0804 02:31:25.849000 140209825414016 torch/distributed/run.py:757] 
W0804 02:31:25.849000 140209825414016 torch/distributed/run.py:757] *****************************************
W0804 02:31:25.849000 140209825414016 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0804 02:31:25.849000 140209825414016 torch/distributed/run.py:757] *****************************************
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188] Starting elastic_operator with launch configs:
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   entrypoint       :  
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   min_nodes        : 2
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   max_nodes        : 2
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   nproc_per_node   : 4
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   run_id           : 19953
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   rdzv_backend     : c10d
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   rdzv_endpoint    : 128.55.67.80:29500
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   rdzv_configs     : {'timeout': 900}
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   max_restarts     : 0
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   monitor_interval : 5
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   log_dir          : /tmp/torchelastic_4svf79xp
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188]   metrics_cfg      : {}
I0804 02:31:25.850000 140209825414016 torch/distributed/launcher/api.py:188] 
W0804 02:31:28.172000 140549842799488 torch/distributed/run.py:757] 
W0804 02:31:28.172000 140549842799488 torch/distributed/run.py:757] *****************************************
W0804 02:31:28.172000 140549842799488 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0804 02:31:28.172000 140549842799488 torch/distributed/run.py:757] *****************************************
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188] Starting elastic_operator with launch configs:
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   entrypoint       :  
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   min_nodes        : 2
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   max_nodes        : 2
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   nproc_per_node   : 4
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   run_id           : 19953
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   rdzv_backend     : c10d
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   rdzv_endpoint    : 128.55.67.80:29500
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   rdzv_configs     : {'timeout': 900}
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   max_restarts     : 0
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   monitor_interval : 5
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   log_dir          : /tmp/torchelastic_iz5ce2qo
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188]   metrics_cfg      : {}
I0804 02:31:28.173000 140549842799488 torch/distributed/launcher/api.py:188] 
I0804 02:31:28.187000 140549842799488 torch/distributed/elastic/agent/server/api.py:866] [default] starting workers for entrypoint: python3.10
I0804 02:31:28.187000 140549842799488 torch/distributed/elastic/agent/server/api.py:699] [default] Rendezvous'ing worker group
I0804 02:31:28.873000 140209825414016 torch/distributed/elastic/agent/server/api.py:866] [default] starting workers for entrypoint: python3.10
I0804 02:31:28.873000 140209825414016 torch/distributed/elastic/agent/server/api.py:699] [default] Rendezvous'ing worker group
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568] [default] Rendezvous complete for workers. Result:
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   restart_count=0
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   master_addr=nid001100-hsn0
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   master_port=39555
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   group_rank=0
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   group_world_size=2
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   local_ranks=[0, 1, 2, 3]
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   role_ranks=[0, 1, 2, 3]
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   global_ranks=[0, 1, 2, 3]
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   role_world_sizes=[8, 8, 8, 8]
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568]   global_world_sizes=[8, 8, 8, 8]
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:568] 
I0804 02:31:30.361000 140549842799488 torch/distributed/elastic/agent/server/api.py:707] [default] Starting worker group
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568] [default] Rendezvous complete for workers. Result:
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   restart_count=0
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   master_addr=nid001100-hsn0
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   master_port=39555
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   group_rank=1
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   group_world_size=2
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   local_ranks=[0, 1, 2, 3]
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   role_ranks=[4, 5, 6, 7]
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/agent/server/local_elastic_agent.py:168] Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   global_ranks=[4, 5, 6, 7]
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   role_world_sizes=[8, 8, 8, 8]
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568]   global_world_sizes=[8, 8, 8, 8]
I0804 02:31:30.361000 140209825414016 torch/distributed/elastic/agent/server/api.py:568] 
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:263] log directory set to: /tmp/torchelastic_iz5ce2qo/19953__10mfi75
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/agent/server/api.py:707] [default] Starting worker group
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker0 reply file to: /tmp/torchelastic_iz5ce2qo/19953__10mfi75/attempt_0/0/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/agent/server/local_elastic_agent.py:168] Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker1 reply file to: /tmp/torchelastic_iz5ce2qo/19953__10mfi75/attempt_0/1/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:263] log directory set to: /tmp/torchelastic_4svf79xp/19953_is_qx96m
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker2 reply file to: /tmp/torchelastic_iz5ce2qo/19953__10mfi75/attempt_0/2/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker0 reply file to: /tmp/torchelastic_4svf79xp/19953_is_qx96m/attempt_0/0/error.json
I0804 02:31:30.362000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker3 reply file to: /tmp/torchelastic_iz5ce2qo/19953__10mfi75/attempt_0/3/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker1 reply file to: /tmp/torchelastic_4svf79xp/19953_is_qx96m/attempt_0/1/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker2 reply file to: /tmp/torchelastic_4svf79xp/19953_is_qx96m/attempt_0/2/error.json
I0804 02:31:30.362000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:358] Setting worker3 reply file to: /tmp/torchelastic_4svf79xp/19953_is_qx96m/attempt_0/3/error.json
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
/global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10: can't open file '/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/ ': [Errno 2] No such file or directory
E0804 02:31:35.375000 140549842799488 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 1231746) of binary: /global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10
E0804 02:31:35.378000 140209825414016 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 1920812) of binary: /global/homes/l/lokeshb/.conda/envs/lokesh/bin/python3.10
I0804 02:31:35.516000 140549842799488 torch/distributed/elastic/multiprocessing/errors/__init__.py:360] ('local_rank %s FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html', 0)
Traceback (most recent call last):
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
I0804 02:31:35.526000 140209825414016 torch/distributed/elastic/multiprocessing/errors/__init__.py:360] ('local_rank %s FAILED with no error file. Decorate your entrypoint fn with @record for traceback info. See: https://pytorch.org/docs/stable/elastic/errors.html', 4)
Traceback (most recent call last):
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/bin/torchrun", line 8, in <module>
    elastic_launch(
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    sys.exit(main())
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    return f(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
  FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-04_02:31:35
  host      : nid001100-hsn0
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 1231747)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-04_02:31:35
  host      : nid001100-hsn0
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 1231748)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-04_02:31:35
  host      : nid001100-hsn0
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 1231749)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-04_02:31:35
  host      : nid001100-hsn0
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1231746)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    run(args)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
  FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-04_02:31:35
  host      : nid002960-hsn0
  rank      : 5 (local_rank: 1)
  exitcode  : 2 (pid: 1920813)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-04_02:31:35
  host      : nid002960-hsn0
  rank      : 6 (local_rank: 2)
  exitcode  : 2 (pid: 1920814)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-04_02:31:35
  host      : nid002960-hsn0
  rank      : 7 (local_rank: 3)
  exitcode  : 2 (pid: 1920815)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-04_02:31:35
  host      : nid002960-hsn0
  rank      : 4 (local_rank: 0)
  exitcode  : 2 (pid: 1920812)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: nid002960: task 1: Exited with exit code 1
srun: Terminating StepId=28986689.1
srun: error: nid001100: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/dist-training.py", line 277, in <module>
    ddp_setup()
  File "/global/u1/l/lokeshb/E2E/E2E_MAE_Lokesh_Badisa/utils/misc.py", line 52, in ddp_setup
    init_process_group(backend="nccl",rank=GLOBAL_RANK,world_size=WORLD_SIZE)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1305, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/global/homes/l/lokeshb/.conda/envs/lokesh/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistStoreError: Timed out after 601 seconds waiting for clients. 1/2 clients joined.
